[[redirects]]
    from = "/api/*"
    to = "https://we-sell-houses-backend.herokuapp.com/:splat"
    status = 200
    force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status=200

